theme:
  logo: assets/wirt_logo.png
  favicon: assets/wirt_logo.png
  name: material  
  palette:
    primary: blue grey
    scheme: slate
  features:
    - navigation.tabs

site_name: Wirt OÜ 
site_description: networking cloud storage consultation
site_url: https://wirt-ee.github.io/

markdown_extensions:
  - meta

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true

extra:
  generator: false

extra_css: [stylesheets/extra.css] 

copyright: If you have any problems or questions, please write to <a href="mailto:info@wirt.ee">info@wirt.ee</a>

