theme:
  logo: assets/wirt_logo.png
  favicon: assets/wirt_logo.png
  name: material  
  features:
    - navigation.tabs
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

site_name: Wirt OÜ 
site_description: networking cloud storage consultation
site_url: https://wirt-ee.github.io/

markdown_extensions:
  - meta

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true

extra:
  generator: false

extra_css: [stylesheets/extra.css] 

copyright: If you have any problems or questions, please write to <a href="mailto:info@wirt.ee">info@wirt.ee</a>

